### ISSUE TITLE
Two people dragging or zooming at the same time will conflict

### ISSUE THREAD

**Issue by cpytel** [jdbann/table#12]
Currently, it's possible for two people to drag or zoom on the map at the same time, causing a conflict.

**Comment by cpytel** [comment]
@jdbann My thinking for how we're going to solve this that each campaign would be associated with a DM and only the DM will have the ability to drag or zoom.

If we want to keep things simple, I don't think all the players need to be able to do this.

What do you think?

**Comment by jdbann** [comment]
@cpytel I'm a bit torn. In general, I'd prefer to avoid restricting it to just the DM that controls the tools. If anything can be done by the party (like tracking initiative, taking notes, managing music etc) then I'd like to have that as an option still.

However, a note from Tom on the first session was that restricting the map (either with controlling the view here, or fog of war #3) would help him focus his action more.

With the map syncing, I would say your proposed approach is probably the right way to handle it. But as a further option, maybe the DM can select:

- DM controls map
- Anyone controls map
- Don't sync map

**Comment by cpytel** [comment]
Agreed on making as many controls as possible accessible to everyone. In practice I think most other things are likely to be more atomic than map movement, not as likely to collide, or be less disruptive if they do, so we will be able to mostly let everyone do things without too much conflict.

In the case of the map, especially for the initially playable version target, I think limiting it to the DM makes sense.

In the future, your options could make sense. Another way to do it would be for the DM to be able to give another player control over the map.

I think other tools give everyone their own view on the map and to move around freely and then the DM has the ability to trigger everyone’s map to snap to theirs. While it’s certainly technically possible for us to do this, in my opinion, we should avoid this because I think it causes players to get confused/lost or fiddle with things. And it’s simpler for the DM to always know everyone is looking at the same thing.

**Comment by cpytel** [comment]
I'm working on adding users now to lay the ground work for this.

**Comment by jdbann** [comment]
I think for initially playable (like the term) we can just ask the players not to move the map. Unless you think adding users will solve anything else?

For the bug, I'd be happy to just add a `being_dragged` attribute to the map record. Or `dragged_at` so we can release it in the event of timeouts.

**Comment by cpytel** [comment]
> I think for initially playable (like the term) we can just ask the players not to move the map. Unless you think adding users will solve anything else?

I was thinking that having users would be nice infrastructure to enable other things as well. In particular, I was hoping to share this with other people I play with to get their thoughts and hopefully use it, and right now everything is accessible and editable by everyone.

Maybe I'm getting ahead of myself, but I would like that ;)

> For the bug, I'd be happy to just add a being_dragged attribute to the map record. Or dragged_at so we can release it in the event of timeouts.

I'm not sure we need to worry about that because refreshing the page would correct that issue and thats probably good enough?

**Comment by jdbann** [comment]
> In particular, I was hoping to share this with other people I play with to get their thoughts and hopefully use it, and right now everything is accessible and editable by everyone.

Ah right! Well that's fair enough. I just didn't want to get caught up in extra associations and permissions. I guess there's a question about what we want from this - should it be a single hosted instance or should a party start their own up?

> I'm not sure we need to worry about that because refreshing the page would correct that issue and thats probably good enough?

To clarify I was suggesting either of those attributes on the DB. So a user can't start a new drag whilst `being_dragged` is true, but that doesn't affect the dragging user. But either way, just something that prevents concurrent drags rather than restricting it to one person who can drag.

**Comment by cpytel** [comment]
> To clarify I was suggesting either of those attributes on the DB. So a user can't start a new drag whilst being_dragged is true, but that doesn't affect the dragging user. But either way, just something that prevents concurrent drags rather than restricting it to one person who can drag.

Ah, I understand now, I like this idea. There is still a possibility that someone would start to drag before they had been told that someone else had started it, but that should be a pretty small edge case.

**Comment by jdbann** [comment]
> There is still a possibility that someone would start to drag before they had been told that someone else had started it, but that should be a pretty small edge case.

That sounds like a fun problem to solve but yeah, shouldn't really come up.

Additionally, we can release a dragged item using the channel's `unsubscribed` callback: https://edgeguides.rubyonrails.org/action_cable_overview.html#example-1-user-appearances

**Comment by cpytel** [comment]
If we plan on doing #15 then is what we discussed here with `being_dragged` necessary?

**Comment by jdbann** [comment]
For now, it wont be necessary. If we open up the map controls to players as well at some point then we'll have to return to this.

The way we discussed will probably be used for the tokens though.
