### ISSUE TITLE
Restrict campaign management to DMs

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#15]
Only registered DMs should be allowed to create new campaigns. Only the DM who created the campaign should be allowed to manage it, including:

- View it in the campaigns index
- Add/edit/remove maps
- Switch current map
- Control current pan and zoom of map

**Comment by cpytel** [comment]
Pulling a comment from @jdbann over from #13 that is related to this:

> Right now I don't see a need to require players to register for accounts, could we keep them public for now?

Just to clarify, you mean keeping the campaign show page public and not requiring users to have an account to interact with the campaign?

**Comment by jdbann** [comment]
> Just to clarify, you mean keeping the campaign show page public and not requiring users to have an account to interact with the campaign?

Yes, until there's any need to identify individual players (for permissions or security) then the campaign show pages should be public.

**Comment by cpytel** [comment]
Sounds good, thanks. I should have a PR for this up today.
