### ISSUE TITLE
Map selector should scroll rather than wrap

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#18]
Currently, the map selector displays available maps (and the new map button) as a grid. The `dev:prime` seeds only include three maps so it looks fine, but adding a fourth makes it wrap on to a new row.

I'd suggest it scrolls horizontally instead. Is that a poor experience for people not using trackpads?

**Comment by cpytel** [comment]
I don't think horizontal scrolling is an issue.

**Comment by jdbann** [comment]
Fixed in 5320b574089a4314e078dcdf0731c08414588f60
