### ISSUE TITLE
Name and domain name

### ISSUE THREAD

**Issue by cpytel** [jdbann/table#20]
In #19 @jdbann asked

> Any thoughts on a domain name? Table is just a name for the project, no idea what we should really call this!

**Comment by cpytel** [comment]
Here are some good options, my most favorite at the top:

- table.party
- dungeon.show
- thetable.show
- themap.live
- themap.show
- thedungeon.live
- thetable.cloud
- trytable.club
- trytable.live
- usetable.live
- usetable.club
- usetable.online
- thedungeon.space
- themap.club
- thedungeon.online
- thegroup.show
- table.rocks

**Comment by jdbann** [comment]
I could get on board with `table.party`

**Comment by cpytel** [comment]
I've registered table.party

**Comment by jdbann** [comment]
I'll get production setup with S3, postgres and redis

**Comment by jdbann** [comment]
Anything I can do to help get this setup @cpytel?

**Comment by cpytel** [comment]
I don't think so. Now that users are merged, I was going to turn my attention to this.

Chad Pytel, Founder and CEO
thoughtbot, inc.
-------------------------------------------
tel: 617.482.1300 x113
fax: 866.217.5992
http://www.thoughtbot.com

**Comment by cpytel** [comment]
@jdbann I noticed that `dev:prime` hasn't been run on production. Just to double-check before I run it, was your intention to run `dev:prime` one time on production, or do you want to manually create it?

**Comment by cpytel** [comment]
https://table.party is now live 🎆

**Comment by jdbann** [comment]
> Just to double-check before I run it, was your intention to run dev:prime one time on production, or do you want to manually create it?

@cpytel Let's not run it. There's nothing which is _required_ for seeding.
