### ISSUE TITLE
Set scale factor for map

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#30]
Maps can now be zoomed, and tokens resize according to that zoom. We cannot adjust the size of the map or the token to ensure that a token fits nicely in the map's grid.

If we could set a scale factor for the map which is only used to adjust the map image's size then we could rescale a map to ensure tokens fit nicely.

For example, a map image is 1200px wide, with a grid size of 20px. The tokens are 36px so don't fit nicely in the map's grid. If we could set a scale factor for the map of 2 then the map would be rendered as 2400px wide, the grid would be 40px and the tokens would fit nicely.

**Comment by cpytel** [comment]
Just reviewing the items in the Playable milestone and had a thought on this. An alternative approach for this might be to actually know the grid size of the map. A fun project would be to see if we could actually look at the image and figure it out automatically by looking for the lines.

If we know the grid size, then we could set the size of the tokens based on that.

Also, if we end up doing #3, then I believe we'll need to know the grid size.

**Comment by jdbann** [comment]
This wouldn't be required to reach **Playable** for our campaign as it has all been built to suit the scale of the maps I get from this campaign.

I'm still feeling anti-grid after my Roll20 experiences 😂

**Comment by jdbann** [comment]
So, a first step might be working with a given size. [Dyson Logos](https://dysonlogos.blog/2020/05/09/the-old-fort-ruins-dungeon/) seems to make maps at 200px per square. The maps from D&D Beyond (or at least the DoIP maps) are at 43px per square.

**Comment by jdbann** [comment]
So maybe there are two issues:

1. Scale maps based on a known px per square value - easier as we can enter a number
2. Scale maps based without a known size - harder as we probably want a visual preview as we change the scale

For 1 we can just add a value to the map form and update the values here https://github.com/jdbann/table/blob/master/app/models/map.rb#L19-L33

**Comment by jdbann** [comment]
Closed by #65
