### ISSUE TITLE
No padding on `.container` looks awkward at some widths

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#37]
<img width="1399" alt="Screenshot 2020-04-12 at 07 55 02" src="https://user-images.githubusercontent.com/1191840/79062505-ebb81280-7c92-11ea-9d64-7c6caf43d9d2.png">

**Comment by cpytel** [comment]
Ah, yes, this worked when it wasn't full width, but not anymore. I'll update it.

**Comment by cpytel** [comment]
Oh, now that I've looked at it I realize that this might not be the problem that I thought it was (the "campaign" layout change) and instead its just actually awkward at some widths based on where the breakpoints are.

**Comment by jdbann** [comment]
Yeah, this is just a note for myself on the pages which use `.container` (just `campaigns#index` I think). Just needs to add some padding.
