### ISSUE TITLE
Plans?

### ISSUE THREAD

**Issue by cpytel** [jdbann/table#5]
Hey @jdbann, I think it'd be good to get a quick overview of how you're expecting the UI to work so that we're on the same page and I can help.

Right now, once you're looking at a campaign you have all the maps along the top, and the current map shown below at 100% width. The overall area has a max-width.

Do you expect all the tokens and such to be on the current map at its size?

What interactions with the map to you expect people to have with the map?

**Comment by cpytel** [comment]
> Do you expect all the tokens and such to be on the current map at its size?

I could also see being able to get a larger, more full-screen version of the current map, like in your original spike.

> What interactions with the map to you expect people to have with the map?

For example, one way I could see this working is basically thinking about the `div` that's currently around the map image being a viewport into the map image, and the map could be moved around within the box or zoomed in on. Doing so would make that the view for all other players (maybe eventually only the DM could do this).

I'm curious to hear your thoughts and plans.

**Comment by jdbann** [comment]
Here's a quick sketch of what I had in mind for the campaign view page:

![Quick UI sketch](https://user-images.githubusercontent.com/1191840/77235003-484f7280-6baa-11ea-95f9-2378561a2961.jpeg)

We have a horizontally scrolling map selector at the top. Selecting one of the maps swaps out the map section underneath.

To the left we have a token drawer. Any tokens attached to the map but not given a location are stored here. They can be dragged from the drawer here to the map.

The map itself is just an image and a scale value, so you could upload an image and present it at 150% (mostly to avoid needing to resize it before uploading).

I'd imagine moving towards role-based permissions and having the map selector and token drawer only visible to the DM.

**Comment by jdbann** [comment]
> Do you expect all the tokens and such to be on the current map at its size?

There will have to be a way to set the size for the map. I'm thinking a percentage or multiplication factor. So Dwarven Excavation is 2,888px wide, but I could set it to 250% to show at 7,220px.

> What interactions with the map to you expect people to have with the map?

The primary interaction will be dragging tokens around. I think a way for users to point at or indicate particular locations would also be helpful. I don't think we need to have the viewport controlled by the DM but that isn't decided.

**Comment by jdbann** [comment]
When we have a way to define an appropriate size for the map, the layout for the page will probably shift into something full screen rather than the centred column we have at the moment.

**Comment by jdbann** [comment]
Ideally, I would like the movement of the tokens to happen in real-time so that a player could further express their character's intentions by jiggling the token around.

For example, to suggest attacking a particular creature, a user could nudge their token towards the creature.

**Comment by cpytel** [comment]
Awesome, the sketch is helpful.

> The map itself is just an image and a scale value, so you could upload an image and present it at 150% (mostly to avoid needing to resize it before uploading).

Makes sense overall. It looks like you're expecting people to be able to scroll around the map (Image inside a scrollable div?). However, in my experience playing remotely, there were often times, particularly when loading a new map, that the tokens would be off in one place on the map placed by the DM and my client wouldn't be scrolled to the right place. IIRC there was a way for the DM to then scroll everyone to the right place, but they needed to explicitly do that.

I think we could potentially simplify this and solve that problem by making it so everyone was always looking at the same thing.

This could be accomplished by scaling the image as you suggest and then setting the scroll position of the scrollable div. This could be synced to everyone (especially if only the DM can scroll around).

I think instead of a scrollable div, I think we should consider making the image a background image on the div. That's going the ability to move it around precisely using `background-position`  and scale it precisely with `background-size`, and sync that display of the map to all of the clients.

I think the map as a background image is going to lead to a better overall interaction model and is worth trying out.

I'm going to explore that now if that's cool.

**Comment by jdbann** [comment]
> I think the map as a background image is going to lead to a better overall interaction model and is worth trying out.

Yes, that sounds like a great option. We'll have to implement dragging the map around, and move all the tokens to match. But if we solved that then we could also do zooming etc.

> I think we could potentially simplify this and solve that problem by making it so everyone was always looking at the same thing.

How about a button or keyboard shortcut to "look here" which moves everyone else's screen to the user's location? We should certainly have some method for doing this.

**Comment by jdbann** [comment]
@cpytel Do you think we've gotten things kicked off enough to close this for now? Or should we be a bit more formal, put together a `Playable` milestone and flesh out what we want in there?

**Comment by cpytel** [comment]
Why not both? I think it makes sense to close this issue and create separate issues with a milestone for anything we identify as necessary for it to be playable.

**Comment by jdbann** [comment]
Added https://github.com/jdbann/table/milestone/1
