### ISSUE TITLE
Switching maps reveals the token drawer to players

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#55]

**Comment by cpytel** [comment]
It looks like what is happening here that `change_current_map` in MapChannel:

```
def change_current_map(data)
    campaign = Campaign.find(data["campaign_id"])
    map = campaign.maps.find(data["map_id"])
    return if !dm?(campaign) || campaign.current_map == map

    campaign.update(current_map: map)
    broadcast_to(
      campaign,
      current_map_html: render_current_map(campaign)
    )
  end
```

is broadcasting the HTML for the map to everyone in the channel when it changes, so this template is being rendered by the DM and sent to all other players.

The way I'm thinking of resolving this is changing `change_current_map` to only broadcast an event for the map change, which would then trigger everyone subscribed to the channel fetch the map HTML for themselves.

Is there a better way?

**Comment by jdbann** [comment]
I was thinking about this as well. We could have separate map channels for the DM and the players? The map channels and controllers have become pretty excessive and we could probably pull them apart.
