### ISSUE TITLE
Support multiple token sizes

### ISSUE THREAD

**Issue by cpytel** [jdbann/table#57]
Monsters can be different sizes, and therefore control a different area in combat, their token should reflect this.

Name | Size | Examples
------|------|-----------
Tiny | 2½ by 2½ ft. | Imp, Sprite
Small | 5 by 5 ft. | Giant Rat, Goblin
Medium | 5 by 5 ft. | Orc, Werewolf
Large | 10 by 10 ft. | Hogriff, Ogre
Huge | 15 by 15 ft. | Fire Giant, Treant
Gargantuan | 20 by 20 ft. or larger | Kraken, Purple Worm

[Source](https://roll20.net/compendium/dnd5e/Monsters#content)

**Comment by cpytel** [comment]
I think this will be relatively straightforward to implement, and it would be nice to have it for our next session, but I'm hesitant to do it right now, with the way the token modeling is now and anticipating that it will change soon.

**Comment by jdbann** [comment]
Here's a question: these sizes are D&D specific. Is Table a D&D specific tool?

**Comment by cpytel** [comment]
I actually don't think they're super D&D specific. While I copied the table from a D&D reference, I think there are a lot of commonalities between RPGs on creature sizes - at least the ones I've ever played.

For example, here is Pathfinder https://www.d20pfsrd.com/gamemastering/combat/space-reach-threatened-area-templates/

The way I was envisioning this in the UI was a dropdown on the token creation screen with the name and then in parenthesis the size after it.

I didn't think Table was a D&D specific tool, but only because it's so minimal that I didn't think that we were doing anything to limit it.

**Comment by jdbann** [comment]
Sorry, I was more thinking RPG vs board games. We could currently setup games like Monopoly or Pandemic etc. Just wondered if we wanted to keep that possibility around or if we're fine to focus on these kind of RPGs specifically.

I think I'm fine with it 👍

**Comment by cpytel** [comment]
I'm comfortable focusing on RPGs

**Comment by jdbann** [comment]
Great! Let's lean in to this then. It would be really helpful if we could get this in for the next session
